// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/matchmakingv1/matchmaking.proto

package matchmakingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchReportService_ReportMatchCreated_FullMethodName      = "/matchmaking.v1.MatchReportService/ReportMatchCreated"
	MatchReportService_ReportMatchmakingFailed_FullMethodName = "/matchmaking.v1.MatchReportService/ReportMatchmakingFailed"
)

// MatchReportServiceClient is the client API for MatchReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MatchReportService is called by chess-server instances after a pairing
// attempt resolves. matchmaking-service has no involvement in *which*
// instance handles a pair (server-picks — PHASE_3_DESIGN_NOTES.md §2) —
// this is purely a report of an outcome that has already happened.
//
// Two methods, not one method with a success/failure oneof: the two
// outcomes share almost no fields and have completely different downstream
// handling on matchmaking-service's side, so a oneof would mostly produce a
// message where half the fields are meaningless depending on branch
// (PHASE_3_DESIGN_NOTES.md §6).
type MatchReportServiceClient interface {
	ReportMatchCreated(ctx context.Context, in *MatchCreatedRequest, opts ...grpc.CallOption) (*MatchCreatedResponse, error)
	ReportMatchmakingFailed(ctx context.Context, in *MatchmakingFailedRequest, opts ...grpc.CallOption) (*MatchmakingFailedResponse, error)
}

type matchReportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchReportServiceClient(cc grpc.ClientConnInterface) MatchReportServiceClient {
	return &matchReportServiceClient{cc}
}

func (c *matchReportServiceClient) ReportMatchCreated(ctx context.Context, in *MatchCreatedRequest, opts ...grpc.CallOption) (*MatchCreatedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchCreatedResponse)
	err := c.cc.Invoke(ctx, MatchReportService_ReportMatchCreated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchReportServiceClient) ReportMatchmakingFailed(ctx context.Context, in *MatchmakingFailedRequest, opts ...grpc.CallOption) (*MatchmakingFailedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchmakingFailedResponse)
	err := c.cc.Invoke(ctx, MatchReportService_ReportMatchmakingFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchReportServiceServer is the server API for MatchReportService service.
// All implementations must embed UnimplementedMatchReportServiceServer
// for forward compatibility.
//
// MatchReportService is called by chess-server instances after a pairing
// attempt resolves. matchmaking-service has no involvement in *which*
// instance handles a pair (server-picks — PHASE_3_DESIGN_NOTES.md §2) —
// this is purely a report of an outcome that has already happened.
//
// Two methods, not one method with a success/failure oneof: the two
// outcomes share almost no fields and have completely different downstream
// handling on matchmaking-service's side, so a oneof would mostly produce a
// message where half the fields are meaningless depending on branch
// (PHASE_3_DESIGN_NOTES.md §6).
type MatchReportServiceServer interface {
	ReportMatchCreated(context.Context, *MatchCreatedRequest) (*MatchCreatedResponse, error)
	ReportMatchmakingFailed(context.Context, *MatchmakingFailedRequest) (*MatchmakingFailedResponse, error)
	mustEmbedUnimplementedMatchReportServiceServer()
}

// UnimplementedMatchReportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchReportServiceServer struct{}

func (UnimplementedMatchReportServiceServer) ReportMatchCreated(context.Context, *MatchCreatedRequest) (*MatchCreatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportMatchCreated not implemented")
}
func (UnimplementedMatchReportServiceServer) ReportMatchmakingFailed(context.Context, *MatchmakingFailedRequest) (*MatchmakingFailedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportMatchmakingFailed not implemented")
}
func (UnimplementedMatchReportServiceServer) mustEmbedUnimplementedMatchReportServiceServer() {}
func (UnimplementedMatchReportServiceServer) testEmbeddedByValue()                            {}

// UnsafeMatchReportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchReportServiceServer will
// result in compilation errors.
type UnsafeMatchReportServiceServer interface {
	mustEmbedUnimplementedMatchReportServiceServer()
}

func RegisterMatchReportServiceServer(s grpc.ServiceRegistrar, srv MatchReportServiceServer) {
	// If the following call pancis, it indicates UnimplementedMatchReportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchReportService_ServiceDesc, srv)
}

func _MatchReportService_ReportMatchCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchCreatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchReportServiceServer).ReportMatchCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchReportService_ReportMatchCreated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchReportServiceServer).ReportMatchCreated(ctx, req.(*MatchCreatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchReportService_ReportMatchmakingFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchmakingFailedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchReportServiceServer).ReportMatchmakingFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchReportService_ReportMatchmakingFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchReportServiceServer).ReportMatchmakingFailed(ctx, req.(*MatchmakingFailedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchReportService_ServiceDesc is the grpc.ServiceDesc for MatchReportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchReportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matchmaking.v1.MatchReportService",
	HandlerType: (*MatchReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportMatchCreated",
			Handler:    _MatchReportService_ReportMatchCreated_Handler,
		},
		{
			MethodName: "ReportMatchmakingFailed",
			Handler:    _MatchReportService_ReportMatchmakingFailed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/matchmakingv1/matchmaking.proto",
}
