// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: proto/matchmakingv1/matchmaking.proto

package matchmakingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum, not a free-form string — CODING_GUIDELINES.md's forbidden-patterns
// table already bans hardcoded strings for state in favor of typed
// constants; no reason to relax that at a service boundary.
//
// Scoped to what chess-server can actually experience over this RPC only
// (RETRIES_EXHAUSTED). Queue-starvation timeouts (QUEUE_TIMEOUT) never
// touch gRPC at all — chess-server never attempted a pairing for a player
// who timed out in the queue, so it has nothing to report here.
// matchmaking-service has its own superset client-facing reason type for
// its SSE/status payloads (PHASE_3_DESIGN_NOTES.md §14), translating
// RETRIES_EXHAUSTED from this enum and generating QUEUE_TIMEOUT natively —
// that type is not this one and is not defined in this proto.
type MatchmakingFailureReason int32

const (
	MatchmakingFailureReason_MATCHMAKING_FAILURE_REASON_UNSPECIFIED MatchmakingFailureReason = 0
	// Only case that exists today. Left as an enum (not a bool) so a second
	// cause later doesn't force a field-shape change.
	MatchmakingFailureReason_MATCHMAKING_FAILURE_REASON_RETRIES_EXHAUSTED MatchmakingFailureReason = 1
)

// Enum value maps for MatchmakingFailureReason.
var (
	MatchmakingFailureReason_name = map[int32]string{
		0: "MATCHMAKING_FAILURE_REASON_UNSPECIFIED",
		1: "MATCHMAKING_FAILURE_REASON_RETRIES_EXHAUSTED",
	}
	MatchmakingFailureReason_value = map[string]int32{
		"MATCHMAKING_FAILURE_REASON_UNSPECIFIED":       0,
		"MATCHMAKING_FAILURE_REASON_RETRIES_EXHAUSTED": 1,
	}
)

func (x MatchmakingFailureReason) Enum() *MatchmakingFailureReason {
	p := new(MatchmakingFailureReason)
	*p = x
	return p
}

func (x MatchmakingFailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchmakingFailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_matchmakingv1_matchmaking_proto_enumTypes[0].Descriptor()
}

func (MatchmakingFailureReason) Type() protoreflect.EnumType {
	return &file_proto_matchmakingv1_matchmaking_proto_enumTypes[0]
}

func (x MatchmakingFailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchmakingFailureReason.Descriptor instead.
func (MatchmakingFailureReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_matchmakingv1_matchmaking_proto_rawDescGZIP(), []int{0}
}

// MatchCreatedRequest reports a successful CreateMatchedGame. game_id is
// the natural idempotency/dedup key on matchmaking-service's side
// (short-TTL "reported:<gameID>" Redis key, checked before pushing SSE) —
// covers a chess-server retry after a lost ACK without double-delivering
// MATCH_FOUND.
//
// Two token pairs, not one — PHASE_3_DESIGN_NOTES.md §18 (2026-08-17):
// *_player_token is the long-lived PlayerClaims (unchanged from this
// proto's original design — same tokens already used for the active-game
// marker, ADR-037), kept as the fallback credential for a LATER reconnect
// via GET /games/{id}/resolve. *_connect_token is a freshly-minted,
// short-lived ConnectClaims (carries instance_label, unlike PlayerClaims)
// — safe to mint here because CreateMatchedGame runs on the exact instance
// that will own the game, synchronously, so there is no staleness window
// between minting and delivery, unlike the marker's read pattern (which
// may be read an arbitrary time after being written and genuinely needs
// PlayerClaims + a fresh /resolve call). matchmaking-service relays
// connect_token as MATCH_FOUND's directly-dialable credential and
// player_token as the fallback if that dial is ever rejected as stale.
type MatchCreatedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId            string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	WhiteUserId       string `protobuf:"bytes,2,opt,name=white_user_id,json=whiteUserId,proto3" json:"white_user_id,omitempty"`
	BlackUserId       string `protobuf:"bytes,3,opt,name=black_user_id,json=blackUserId,proto3" json:"black_user_id,omitempty"`
	WhitePlayerToken  string `protobuf:"bytes,4,opt,name=white_player_token,json=whitePlayerToken,proto3" json:"white_player_token,omitempty"` // signed PlayerClaims — renamed from white_token (§18); same value/shape, honest name
	BlackPlayerToken  string `protobuf:"bytes,5,opt,name=black_player_token,json=blackPlayerToken,proto3" json:"black_player_token,omitempty"`
	WhiteConnectToken string `protobuf:"bytes,7,opt,name=white_connect_token,json=whiteConnectToken,proto3" json:"white_connect_token,omitempty"` // signed ConnectClaims — NEW (§18), directly dialable, no /resolve needed
	BlackConnectToken string `protobuf:"bytes,8,opt,name=black_connect_token,json=blackConnectToken,proto3" json:"black_connect_token,omitempty"`
	// instance_label, not instance_id — matches the field name already used
	// end-to-end in the real codebase (auth.ConnectClaims.InstanceLabel,
	// Manager.ResolveGame's instanceLabel return value, nginx.conf's
	// $instance_label / ADR-022's "instanceLabel is opaque" language),
	// confirmed by direct read of resolve.go and nginx.conf.
	InstanceLabel string `protobuf:"bytes,6,opt,name=instance_label,json=instanceLabel,proto3" json:"instance_label,omitempty"`
}

func (x *MatchCreatedRequest) Reset() {
	*x = MatchCreatedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_matchmakingv1_matchmaking_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchCreatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCreatedRequest) ProtoMessage() {}

func (x *MatchCreatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmakingv1_matchmaking_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCreatedRequest.ProtoReflect.Descriptor instead.
func (*MatchCreatedRequest) Descriptor() ([]byte, []int) {
	return file_proto_matchmakingv1_matchmaking_proto_rawDescGZIP(), []int{0}
}

func (x *MatchCreatedRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *MatchCreatedRequest) GetWhiteUserId() string {
	if x != nil {
		return x.WhiteUserId
	}
	return ""
}

func (x *MatchCreatedRequest) GetBlackUserId() string {
	if x != nil {
		return x.BlackUserId
	}
	return ""
}

func (x *MatchCreatedRequest) GetWhitePlayerToken() string {
	if x != nil {
		return x.WhitePlayerToken
	}
	return ""
}

func (x *MatchCreatedRequest) GetBlackPlayerToken() string {
	if x != nil {
		return x.BlackPlayerToken
	}
	return ""
}

func (x *MatchCreatedRequest) GetWhiteConnectToken() string {
	if x != nil {
		return x.WhiteConnectToken
	}
	return ""
}

func (x *MatchCreatedRequest) GetBlackConnectToken() string {
	if x != nil {
		return x.BlackConnectToken
	}
	return ""
}

func (x *MatchCreatedRequest) GetInstanceLabel() string {
	if x != nil {
		return x.InstanceLabel
	}
	return ""
}

type MatchCreatedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acknowledged bool `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
}

func (x *MatchCreatedResponse) Reset() {
	*x = MatchCreatedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_matchmakingv1_matchmaking_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchCreatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCreatedResponse) ProtoMessage() {}

func (x *MatchCreatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmakingv1_matchmaking_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCreatedResponse.ProtoReflect.Descriptor instead.
func (*MatchCreatedResponse) Descriptor() ([]byte, []int) {
	return file_proto_matchmakingv1_matchmaking_proto_rawDescGZIP(), []int{1}
}

func (x *MatchCreatedResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

// MatchmakingFailedRequest reports a confirmed, terminal failure of
// CreateMatchedGame's atomic DB insert after retries are exhausted —
// mirrors CreateGame's existing failure semantics (ADR-028). Must NOT fire
// for every transient/retryable insert failure; chess-server owns
// re-enqueue directly for those (PHASE_3_DESIGN_NOTES.md §8) and this RPC
// is never involved in that path.
type MatchmakingFailedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WhiteUserId string                   `protobuf:"bytes,1,opt,name=white_user_id,json=whiteUserId,proto3" json:"white_user_id,omitempty"`
	BlackUserId string                   `protobuf:"bytes,2,opt,name=black_user_id,json=blackUserId,proto3" json:"black_user_id,omitempty"`
	Reason      MatchmakingFailureReason `protobuf:"varint,3,opt,name=reason,proto3,enum=matchmaking.v1.MatchmakingFailureReason" json:"reason,omitempty"`
}

func (x *MatchmakingFailedRequest) Reset() {
	*x = MatchmakingFailedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_matchmakingv1_matchmaking_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchmakingFailedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchmakingFailedRequest) ProtoMessage() {}

func (x *MatchmakingFailedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmakingv1_matchmaking_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchmakingFailedRequest.ProtoReflect.Descriptor instead.
func (*MatchmakingFailedRequest) Descriptor() ([]byte, []int) {
	return file_proto_matchmakingv1_matchmaking_proto_rawDescGZIP(), []int{2}
}

func (x *MatchmakingFailedRequest) GetWhiteUserId() string {
	if x != nil {
		return x.WhiteUserId
	}
	return ""
}

func (x *MatchmakingFailedRequest) GetBlackUserId() string {
	if x != nil {
		return x.BlackUserId
	}
	return ""
}

func (x *MatchmakingFailedRequest) GetReason() MatchmakingFailureReason {
	if x != nil {
		return x.Reason
	}
	return MatchmakingFailureReason_MATCHMAKING_FAILURE_REASON_UNSPECIFIED
}

type MatchmakingFailedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acknowledged bool `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
}

func (x *MatchmakingFailedResponse) Reset() {
	*x = MatchmakingFailedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_matchmakingv1_matchmaking_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchmakingFailedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchmakingFailedResponse) ProtoMessage() {}

func (x *MatchmakingFailedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmakingv1_matchmaking_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchmakingFailedResponse.ProtoReflect.Descriptor instead.
func (*MatchmakingFailedResponse) Descriptor() ([]byte, []int) {
	return file_proto_matchmakingv1_matchmaking_proto_rawDescGZIP(), []int{3}
}

func (x *MatchmakingFailedResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_proto_matchmakingv1_matchmaking_proto protoreflect.FileDescriptor

var file_proto_matchmakingv1_matchmaking_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b,
	0x69, 0x6e, 0x67, 0x76, 0x31, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x69, 0x6e,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x22, 0xd9, 0x02, 0x0a, 0x13, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x77, 0x68, 0x69, 0x74,
	0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x77, 0x68, 0x69, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d,
	0x62, 0x6c, 0x61, 0x63, 0x6b, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x2c, 0x0a, 0x12, 0x77, 0x68, 0x69, 0x74, 0x65, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x77, 0x68,
	0x69, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2c,
	0x0a, 0x12, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x62, 0x6c, 0x61, 0x63,
	0x6b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2e, 0x0a, 0x13,
	0x77, 0x68, 0x69, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x77, 0x68, 0x69, 0x74, 0x65,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2e, 0x0a, 0x13,
	0x62, 0x6c, 0x61, 0x63, 0x6b, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x62, 0x6c, 0x61, 0x63, 0x6b,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x25, 0x0a, 0x0e,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x22, 0x3a, 0x0a, 0x14, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x61,
	0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0c, 0x61, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x64, 0x22,
	0xa4, 0x01, 0x0a, 0x18, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x46,
	0x61, 0x69, 0x6c, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0d,
	0x77, 0x68, 0x69, 0x74, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x77, 0x68, 0x69, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x22, 0x0a, 0x0d, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x40, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x69, 0x6e,
	0x67, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x3f, 0x0a, 0x19, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x6d,
	0x61, 0x6b, 0x69, 0x6e, 0x67, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x61, 0x63, 0x6b, 0x6e, 0x6f,
	0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x64, 0x2a, 0x78, 0x0a, 0x18, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x6d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x52, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x26, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x4d, 0x41, 0x4b, 0x49,
	0x4e, 0x47, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f,
	0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x30, 0x0a, 0x2c, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x4d, 0x41, 0x4b, 0x49, 0x4e, 0x47, 0x5f, 0x46,
	0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x52, 0x45,
	0x54, 0x52, 0x49, 0x45, 0x53, 0x5f, 0x45, 0x58, 0x48, 0x41, 0x55, 0x53, 0x54, 0x45, 0x44, 0x10,
	0x01, 0x32, 0xe5, 0x01, 0x0a, 0x12, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5f, 0x0a, 0x12, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x23,
	0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x69, 0x6e,
	0x67, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6e, 0x0a, 0x17, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x46, 0x61,
	0x69, 0x6c, 0x65, 0x64, 0x12, 0x28, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x69, 0x6e,
	0x67, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29,
	0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x46, 0x61, 0x69, 0x6c, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x65, 0x64, 0x61, 0x6e, 0x74, 0x2d, 0x32,
	0x37, 0x30, 0x31, 0x2f, 0x63, 0x68, 0x65, 0x73, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x76, 0x31, 0x3b, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_matchmakingv1_matchmaking_proto_rawDescOnce sync.Once
	file_proto_matchmakingv1_matchmaking_proto_rawDescData = file_proto_matchmakingv1_matchmaking_proto_rawDesc
)

func file_proto_matchmakingv1_matchmaking_proto_rawDescGZIP() []byte {
	file_proto_matchmakingv1_matchmaking_proto_rawDescOnce.Do(func() {
		file_proto_matchmakingv1_matchmaking_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_matchmakingv1_matchmaking_proto_rawDescData)
	})
	return file_proto_matchmakingv1_matchmaking_proto_rawDescData
}

var file_proto_matchmakingv1_matchmaking_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_matchmakingv1_matchmaking_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_matchmakingv1_matchmaking_proto_goTypes = []any{
	(MatchmakingFailureReason)(0),     // 0: matchmaking.v1.MatchmakingFailureReason
	(*MatchCreatedRequest)(nil),       // 1: matchmaking.v1.MatchCreatedRequest
	(*MatchCreatedResponse)(nil),      // 2: matchmaking.v1.MatchCreatedResponse
	(*MatchmakingFailedRequest)(nil),  // 3: matchmaking.v1.MatchmakingFailedRequest
	(*MatchmakingFailedResponse)(nil), // 4: matchmaking.v1.MatchmakingFailedResponse
}
var file_proto_matchmakingv1_matchmaking_proto_depIdxs = []int32{
	0, // 0: matchmaking.v1.MatchmakingFailedRequest.reason:type_name -> matchmaking.v1.MatchmakingFailureReason
	1, // 1: matchmaking.v1.MatchReportService.ReportMatchCreated:input_type -> matchmaking.v1.MatchCreatedRequest
	3, // 2: matchmaking.v1.MatchReportService.ReportMatchmakingFailed:input_type -> matchmaking.v1.MatchmakingFailedRequest
	2, // 3: matchmaking.v1.MatchReportService.ReportMatchCreated:output_type -> matchmaking.v1.MatchCreatedResponse
	4, // 4: matchmaking.v1.MatchReportService.ReportMatchmakingFailed:output_type -> matchmaking.v1.MatchmakingFailedResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_matchmakingv1_matchmaking_proto_init() }
func file_proto_matchmakingv1_matchmaking_proto_init() {
	if File_proto_matchmakingv1_matchmaking_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_matchmakingv1_matchmaking_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MatchCreatedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_matchmakingv1_matchmaking_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MatchCreatedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_matchmakingv1_matchmaking_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*MatchmakingFailedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_matchmakingv1_matchmaking_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*MatchmakingFailedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_matchmakingv1_matchmaking_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_matchmakingv1_matchmaking_proto_goTypes,
		DependencyIndexes: file_proto_matchmakingv1_matchmaking_proto_depIdxs,
		EnumInfos:         file_proto_matchmakingv1_matchmaking_proto_enumTypes,
		MessageInfos:      file_proto_matchmakingv1_matchmaking_proto_msgTypes,
	}.Build()
	File_proto_matchmakingv1_matchmaking_proto = out.File
	file_proto_matchmakingv1_matchmaking_proto_rawDesc = nil
	file_proto_matchmakingv1_matchmaking_proto_goTypes = nil
	file_proto_matchmakingv1_matchmaking_proto_depIdxs = nil
}
